name: tikweb_task
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  hive_flutter: ^1.1.0
  get_it: ^8.2.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  shimmer: ^3.0.0
  equatable: ^2.0.7
  hive: ^2.2.3
  path_provider: ^2.1.5
  mockito: ^5.4.5
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  bloc_test: ^10.0.0

flutter:


  uses-material-design: true

